name: libghostty
description: Dart bindings to libghostty-vt, the terminal emulator library from Ghostty.
version: 0.0.9
repository: https://github.com/elias8/libghostty/tree/main/packages/libghostty
resolution: workspace

# This package supports all platforms listed below.
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

topics:
  - terminal
  - emulator
  - ffi
  - ghostty
  - libghostty

environment:
  sdk: ^3.11.0

dependencies:
  code_assets: ^1.0.0
  crypto: ^3.0.7
  ffi: ^2.2.0
  hooks: ^1.0.2
  meta: ^1.16.0
  web: ^1.1.1

dev_dependencies:
  ffigen: ^20.1.1
  logging: ^1.3.0
  path: ^1.9.1
  shelf: ^1.4.2
  shelf_static: ^1.1.3
  stream_channel: ^2.1.4
  test: ^1.25.6
