// --- DO NOT EDIT MANUALLY ---
// This file contains hashes of libghostty binaries downloaded by the build
// hook. For tests, it is replaced with actual assets built from the tarballs.
// For releases, a pre-release check asserts it's up-to-date.
//
// Generated by tool/generate_binary_hash.dart

// dart format off
// ignore_for_file: unnecessary_ignore, lines_longer_than_80_chars

/// The release tag used for downloading prebuilt binaries.
const releaseTag = 'libghostty-v0.0.6';

/// SHA256 hashes for pre-built native binaries. Keys are the artifact
/// filenames.
const assetHashes = <String, String>{
  'libghostty-aarch64-ios-simulator.dylib': '5d9c12a1c98eeeba26f9490df42286bdaf472a5c287c147f5df2fc19ca38ce8c',
  'libghostty-aarch64-ios.dylib': '6e72927261615a9e0b2fc2977b7a234daac5986181cb12d32b842bc42fb36ad4',
  'libghostty-aarch64-linux-android.so': '2fb09b0737bdbd1445191aeecce0ae1d872f5d26925d17a4cd561b9e05d64868',
  'libghostty-aarch64-linux.so': 'b650eda552d3c316ad4ec493dbcd941ece3cd93ebbb13070f93615194b6b1b9f',
  'libghostty-aarch64-macos.dylib': '57c81c3e0d257153a2a58a6059f53a36cfd869a32bf4776de5eec709f5467001',
  'libghostty-arm-linux-androideabi.so': '47466e35dfb2586f39b11e629224ddecc3188e0d8a5bca1d5191acb2e48f2f8b',
  'libghostty-wasm32-freestanding.wasm': '265255029ea8116be5a20985294c77c43328b511f4f6494c52c554306183b58c',
  'libghostty-x86_64-ios-simulator.dylib': 'f92e7993927b4f4ca24c613e2942437bde6c87e4cc4082bcc8fdbb40506b0bde',
  'libghostty-x86_64-linux-android.so': '094966211f3d83548b440e9768176c080ef97f92eca20eaac6780c6d11a67170',
  'libghostty-x86_64-linux-musl.so': 'a315cd37399e5a3b972ac3fa5553615e035db2b5bdfa19201331f77c1adc458a',
  'libghostty-x86_64-linux.so': 'b3b0bc3155f930b92a08a30068257c760c687f6556e38e0c134f8d1a512f9efd',
  'libghostty-x86_64-macos.dylib': '489b252e5b18ce56ba78c57e20f053941afc3837a8a25071c29be6310033efbe',
  'libghostty-x86_64-windows.dll': '9f9af14ee1a22a3fec186c95b9b92b71068dd22c4da11dbe0732bf4ca17bf73a',
};
