name: flterm
description: A high-performance terminal emulator renderer for Flutter, powered by libghostty-vt.
version: 0.0.1-dev.1
homepage: https://github.com/elias8/libghostty
repository: https://github.com/elias8/libghostty/tree/main/packages/flterm
issue_tracker: https://github.com/elias8/libghostty/issues
resolution: workspace

# This package supports all platforms listed below.
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

topics:
  - terminal
  - terminal-emulator
  - ghostty
  - libghostty
  - vt100

environment:
  sdk: ^3.11.0
  flutter: ">=3.27.0"

dependencies:
  flutter:
    sdk: flutter
  libghostty: ^0.0.7
  meta: ^1.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
