name: flterm_example
description: Example app for flterm.
version: 0.0.1-dev.1
resolution: workspace
publish_to: none

environment:
  sdk: ^3.10.0
  flutter: ">=3.32.0"

dependencies:
  flterm:
    path: ..
  flutter:
    sdk: flutter
  libghostty: ^0.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
