import 'dart:typed_data';

import 'package:meta/meta.dart';

import 'cursor.dart';
import 'modes.dart';
import 'mouse.dart';

/// Event emitted by [Terminal.onEvent] when terminal state changes.
///
/// ```dart
/// terminal.onEvent.listen((event) {
///   switch (event) {
///     case BellReceived():                    playBeep();
///     case TitleChanged(:final title):         setWindowTitle(title);
///     case CursorChanged(:final cursor):       updateCursor(cursor);
///     case MouseShapeChanged(:final shape):    setCursor(shape);
///     case ModeChanged(:final modes):          syncModes(modes);
///     case ResponseReceived(:final response):  sendToPty(response);
///     case ScreenChanged():                    scheduleRepaint();
///   }
/// });
/// ```
@immutable
sealed class TerminalEvent {
  const TerminalEvent();
}

/// BEL character (0x07) was received.
final class BellReceived extends TerminalEvent {
  const BellReceived();

  @override
  bool operator ==(Object other) => other is BellReceived;

  @override
  int get hashCode => runtimeType.hashCode;
}

/// Window title changed via OSC 0/2.
final class TitleChanged extends TerminalEvent {
  final String title;

  const TitleChanged(this.title);

  @override
  bool operator ==(Object other) =>
      other is TitleChanged && other.title == title;

  @override
  int get hashCode => title.hashCode;
}

/// Cursor position, visibility, or shape changed.
final class CursorChanged extends TerminalEvent {
  final Cursor cursor;

  const CursorChanged(this.cursor);

  @override
  bool operator ==(Object other) =>
      other is CursorChanged && other.cursor == cursor;

  @override
  int get hashCode => cursor.hashCode;
}

/// Mouse pointer shape changed via OSC 22.
final class MouseShapeChanged extends TerminalEvent {
  final MouseShape shape;

  const MouseShapeChanged(this.shape);

  @override
  bool operator ==(Object other) =>
      other is MouseShapeChanged && other.shape == shape;

  @override
  int get hashCode => shape.hashCode;
}

/// Terminal mode changed (DECSET/DECRST/SM/RM).
final class ModeChanged extends TerminalEvent {
  final TerminalModes modes;

  const ModeChanged(this.modes);

  @override
  bool operator ==(Object other) =>
      other is ModeChanged && other.modes == modes;

  @override
  int get hashCode => modes.hashCode;
}

/// Response bytes generated by escape sequences (DA, DSR, etc).
///
/// Write [response] back to the PTY so the host application receives
/// the terminal's reply.
final class ResponseReceived extends TerminalEvent {
  final Uint8List response;

  const ResponseReceived(this.response);

  @override
  bool operator ==(Object other) =>
      other is ResponseReceived && _bytesEqual(other.response, response);

  @override
  int get hashCode => Object.hashAll(response);
}

/// Screen content changed: read the [Terminal.screen] for updated cells.
final class ScreenChanged extends TerminalEvent {
  const ScreenChanged();

  @override
  bool operator ==(Object other) => other is ScreenChanged;

  @override
  int get hashCode => runtimeType.hashCode;
}

bool _bytesEqual(Uint8List a, Uint8List b) {
  if (identical(a, b)) return true;
  if (a.length != b.length) return false;
  for (var i = 0; i < a.length; i++) {
    if (a[i] != b[i]) return false;
  }
  return true;
}
