import 'dart:typed_data';

import 'cursor.dart';
import 'mouse.dart';

/// Event emitted by [Terminal.onEvent] when terminal state changes.
///
/// ```dart
/// terminal.onEvent.listen((event) {
///   switch (event) {
///     case BellReceived():    playBeep();
///     case TitleChanged(:final title): setWindowTitle(title);
///     case CursorChanged(:final cursor): updateCursor(cursor);
///     case MouseShapeChanged(:final shape): setCursor(shape);
///     case ResponseReceived(:final response): sendToPty(response);
///     case ScreenChanged():   scheduleRepaint();
///   }
/// });
/// ```
sealed class TerminalEvent {
  const TerminalEvent();
}

/// BEL character (0x07) was received.
final class BellReceived extends TerminalEvent {
  const BellReceived();
}

/// Window title changed via OSC 0/2.
final class TitleChanged extends TerminalEvent {
  final String title;

  const TitleChanged(this.title);
}

/// Cursor position, visibility, or shape changed.
final class CursorChanged extends TerminalEvent {
  final Cursor cursor;

  const CursorChanged(this.cursor);
}

/// Mouse pointer shape changed via OSC 22.
final class MouseShapeChanged extends TerminalEvent {
  final MouseShape shape;

  const MouseShapeChanged(this.shape);
}

/// Terminal mode changed (DECSET/DECRST/SM/RM).
final class ModeChanged extends TerminalEvent {
  const ModeChanged();
}

/// Response bytes generated by escape sequences (DA, DSR, etc).
///
/// Write [response] back to the PTY so the host application receives
/// the terminal's reply.
final class ResponseReceived extends TerminalEvent {
  final Uint8List response;

  const ResponseReceived(this.response);
}

/// Screen content changed — read the screen for updated cells.
final class ScreenChanged extends TerminalEvent {
  const ScreenChanged();
}
