import 'package:meta/meta.dart';

import '../../bindings/bindings.dart';
import '../../ffi/libghostty_enums.g.dart';
import 'mods.dart';

@internal
int keyEventHandle(KeyEvent event) => event._handle;

/// A keyboard input event containing physical key information, modifiers, and
/// generated text for terminal key encoding.
///
/// Set the event properties and pass it to [KeyEncoder.encode] to produce a
/// terminal escape sequence. Events can be reused across multiple
/// [KeyEncoder.encode] calls by changing their properties between calls.
///
/// Throws [OutOfMemoryException] if the native allocation fails during
/// construction.
///
/// ```dart
/// final event = KeyEvent()
///   ..action = KeyAction.press
///   ..key = Key.c
///   ..mods = Mods.ctrl();
///
/// final seq = encoder.encode(event);
/// if (seq.isNotEmpty) pty.write(utf8.encode(seq));
///
/// event.dispose();
/// ```
class KeyEvent {
  static final _finalizer = Finalizer<int>(bindings.keyEventFree);

  final int _handle;
  var _disposed = false;

  /// Creates a new key event with default values.
  ///
  /// Set the event properties ([action], [key], [mods], etc.) before passing
  /// to [KeyEncoder.encode]. Events can be reused by changing their properties
  /// between encode calls.
  ///
  /// Throws [OutOfMemoryException] if the native allocation fails.
  KeyEvent() : _handle = _create() {
    _finalizer.attach(this, _handle, detach: this);
  }

  /// The key action: [KeyAction.press], [KeyAction.release], or
  /// [KeyAction.repeat].
  KeyAction get action => bindings.keyEventGetAction(_handle);

  /// Sets the key action (press, release, repeat).
  set action(KeyAction value) => bindings.keyEventSetAction(_handle, value);

  /// Whether this event is part of a composition sequence (e.g. dead keys,
  /// IME input).
  bool get composing => bindings.keyEventGetComposing(_handle);

  /// Sets whether this event is part of a composition sequence.
  set composing(bool value) {
    bindings.keyEventSetComposing(_handle, composing: value);
  }

  /// Modifiers consumed by the platform during key processing.
  ///
  /// For example, Shift is consumed when producing an uppercase letter. The
  /// encoder uses this to avoid double-reporting modifiers that the platform
  /// already handled.
  Mods get consumedMods {
    return Mods.fromValue(bindings.keyEventGetConsumedMods(_handle));
  }

  /// Sets the consumed modifiers bitmask.
  set consumedMods(Mods value) {
    bindings.keyEventSetConsumedMods(_handle, value.value);
  }

  /// Physical, layout-independent key code based on the W3C UI Events
  /// KeyboardEvent code standard.
  ///
  /// Represents the physical key position, not the character it produces. For
  /// example, [Key.a] on a US keyboard and the equivalent position on a
  /// Russian keyboard both report the same key code. Layout-dependent text
  /// is provided separately via [utf8].
  Key get key => bindings.keyEventGetKey(_handle);

  /// Sets the physical key code.
  set key(Key value) => bindings.keyEventSetKey(_handle, value);

  /// Active modifier keys at the time of the event.
  Mods get mods => Mods.fromValue(bindings.keyEventGetMods(_handle));

  /// Sets the modifier keys bitmask.
  set mods(Mods value) => bindings.keyEventSetMods(_handle, value.value);

  /// Unicode codepoint for this key without Shift applied.
  int get unshiftedCodepoint => bindings.keyEventGetUnshiftedCodepoint(_handle);

  /// Sets the unshifted Unicode codepoint.
  set unshiftedCodepoint(int value) {
    bindings.keyEventSetUnshiftedCodepoint(_handle, value);
  }

  /// UTF-8 text generated by the keyboard layout for this key.
  ///
  /// Returns null when no text is set. The returned value is valid until the
  /// event is disposed or the text is modified via the setter.
  String? get utf8 => bindings.keyEventGetUtf8(_handle);

  /// Sets the UTF-8 text generated by the keyboard layout for this key, or
  /// null to clear it.
  ///
  /// Must contain the unmodified character before any Ctrl/Meta
  /// transformations. The encoder derives modifier sequences from the logical
  /// [key] and [mods] bitmask, not from this text.
  ///
  /// Do not pass C0 control characters (U+0000-U+001F, U+007F) or platform
  /// function key codes (e.g. macOS PUA U+F700-U+F8FF); pass null instead and
  /// let the encoder use the logical key.
  ///
  /// The string is copied into the event.
  set utf8(String? value) => bindings.keyEventSetUtf8(_handle, value);

  /// Releases all resources associated with this key event.
  ///
  /// The event must not be used after this call. Safe to call multiple
  /// times; subsequent calls are no-ops.
  void dispose() {
    if (_disposed) return;
    _disposed = true;
    _finalizer.detach(this);
    bindings.keyEventFree(_handle);
  }

  static int _create() => check(bindings.keyEventNew());
}
