// Generated by tool/ffigen.dart. Do not edit.
// Platform-independent enum definitions extracted from libghostty.g.dart.

/// Build info data types that can be queried.
///
/// Each variant documents the expected output pointer type.
enum BuildInfo {
  /// Invalid data type. Never results in any data extraction.
  invalid(0),

  /// Whether SIMD-accelerated code paths are enabled.
  ///
  /// Output type: bool *
  simd(1),

  /// Whether Kitty graphics protocol support is available.
  ///
  /// Output type: bool *
  kittyGraphics(2),

  /// Whether tmux control mode support is available.
  ///
  /// Output type: bool *
  tmuxControlMode(3),

  /// The optimization mode the library was built with.
  ///
  /// Output type: OptimizeMode *
  optimize(4),

  /// The full version string (e.g. "1.2.3" or "1.2.3-dev+abcdef").
  ///
  /// Output type: String *
  versionString(5),

  /// The major version number.
  ///
  /// Output type: size_t *
  versionMajor(6),

  /// The minor version number.
  ///
  /// Output type: size_t *
  versionMinor(7),

  /// The patch version number.
  ///
  /// Output type: size_t *
  versionPatch(8),

  /// The pre metadata string (e.g. "alpha", "beta", "dev"). Has zero length if
  /// no pre metadata is present.
  ///
  /// Output type: String *
  versionPre(9),

  /// The build metadata string (e.g. commit hash). Has zero length if
  /// no build metadata is present.
  ///
  /// Output type: String *
  versionBuild(10);

  final int value;
  const BuildInfo(this.value);

  static BuildInfo fromValue(int value) => switch (value) {
    0 => invalid,
    1 => simd,
    2 => kittyGraphics,
    3 => tmuxControlMode,
    4 => optimize,
    5 => versionString,
    6 => versionMajor,
    7 => versionMinor,
    8 => versionPatch,
    9 => versionPre,
    10 => versionBuild,
    _ => throw ArgumentError('Unknown value for BuildInfo: $value'),
  };
}

/// Cell content tag.
///
/// Describes what kind of content a cell holds.
///
/// @ingroup screen
enum CellContentTag {
  /// A single codepoint (may be zero for empty).
  codepoint(0),

  /// A codepoint that is part of a multi-codepoint grapheme cluster.
  codepointGrapheme(1),

  /// No text; background color from palette.
  bgColorPalette(2),

  /// No text; background color as RGB.
  bgColorRgb(3);

  final int value;
  const CellContentTag(this.value);

  static CellContentTag fromValue(int value) => switch (value) {
    0 => codepoint,
    1 => codepointGrapheme,
    2 => bgColorPalette,
    3 => bgColorRgb,
    _ => throw ArgumentError('Unknown value for CellContentTag: $value'),
  };
}

/// Cell data types.
///
/// These values specify what type of data to extract from a cell
/// using `ghostty_cell_get`.
///
/// @ingroup screen
enum CellData {
  /// Invalid data type. Never results in any data extraction.
  invalid(0),

  /// The codepoint of the cell (0 if empty or bg-color-only).
  ///
  /// Output type: uint32_t *
  codepoint(1),

  /// The content tag describing what kind of content is in the cell.
  ///
  /// Output type: CellContentTag *
  contentTag(2),

  /// The wide property of the cell.
  ///
  /// Output type: CellWide *
  wide(3),

  /// Whether the cell has text to render.
  ///
  /// Output type: bool *
  hasText(4),

  /// Whether the cell has non-default styling.
  ///
  /// Output type: bool *
  hasStyling(5),

  /// The style ID for the cell (for use with style lookups).
  ///
  /// Output type: uint16_t *
  styleId(6),

  /// Whether the cell has a hyperlink.
  ///
  /// Output type: bool *
  hasHyperlink(7),

  /// Whether the cell is protected.
  ///
  /// Output type: bool *
  protected(8),

  /// The semantic content type of the cell (from OSC 133).
  ///
  /// Output type: CellSemanticContent *
  semanticContent(9),

  /// The palette index for the cell's background color.
  /// Only valid when content_tag is GHOSTTY_CELL_CONTENT_BG_COLOR_PALETTE.
  ///
  /// Output type: ColorPaletteIndex *
  colorPalette(10),

  /// The RGB value for the cell's background color.
  /// Only valid when content_tag is GHOSTTY_CELL_CONTENT_BG_COLOR_RGB.
  ///
  /// Output type: ColorRgb *
  colorRgb(11);

  final int value;
  const CellData(this.value);

  static CellData fromValue(int value) => switch (value) {
    0 => invalid,
    1 => codepoint,
    2 => contentTag,
    3 => wide,
    4 => hasText,
    5 => hasStyling,
    6 => styleId,
    7 => hasHyperlink,
    8 => protected,
    9 => semanticContent,
    10 => colorPalette,
    11 => colorRgb,
    _ => throw ArgumentError('Unknown value for CellData: $value'),
  };
}

/// Semantic content type of a cell.
///
/// Set by semantic prompt sequences (OSC 133) to distinguish between
/// command output, user input, and shell prompt text.
///
/// @ingroup screen
enum CellSemanticContent {
  /// Regular output content, such as command output.
  output(0),

  /// Content that is part of user input.
  input(1),

  /// Content that is part of a shell prompt.
  prompt(2);

  final int value;
  const CellSemanticContent(this.value);

  static CellSemanticContent fromValue(int value) => switch (value) {
    0 => output,
    1 => input,
    2 => prompt,
    _ => throw ArgumentError('Unknown value for CellSemanticContent: $value'),
  };
}

/// Cell wide property.
///
/// Describes the width behavior of a cell.
///
/// @ingroup screen
enum CellWide {
  /// Not a wide character, cell width 1.
  narrow(0),

  /// Wide character, cell width 2.
  wide(1),

  /// Spacer after wide character. Do not render.
  spacerTail(2),

  /// Spacer at end of soft-wrapped line for a wide character.
  spacerHead(3);

  final int value;
  const CellWide(this.value);

  static CellWide fromValue(int value) => switch (value) {
    0 => narrow,
    1 => wide,
    2 => spacerTail,
    3 => spacerHead,
    _ => throw ArgumentError('Unknown value for CellWide: $value'),
  };
}

/// Color scheme reported in response to a CSI ? 996 n query.
///
/// @ingroup terminal
enum ColorScheme {
  light(0),
  dark(1);

  final int value;
  const ColorScheme(this.value);

  static ColorScheme fromValue(int value) => switch (value) {
    0 => light,
    1 => dark,
    _ => throw ArgumentError('Unknown value for ColorScheme: $value'),
  };
}

/// Focus event types for focus reporting mode (mode 1004).
enum FocusEvent {
  /// Terminal window gained focus
  gained(0),

  /// Terminal window lost focus
  lost(1);

  final int value;
  const FocusEvent(this.value);

  static FocusEvent fromValue(int value) => switch (value) {
    0 => gained,
    1 => lost,
    _ => throw ArgumentError('Unknown value for FocusEvent: $value'),
  };
}

/// Terminal content output format.
///
/// @ingroup formatter
enum FormatterFormat {
  /// Plain text (no escape sequences).
  plain(0),

  /// VT sequences preserving colors, styles, URLs, etc.
  vt(1),

  /// HTML with inline styles.
  html(2);

  final int value;
  const FormatterFormat(this.value);

  static FormatterFormat fromValue(int value) => switch (value) {
    0 => plain,
    1 => vt,
    2 => html,
    _ => throw ArgumentError('Unknown value for FormatterFormat: $value'),
  };
}

/// Physical key codes.
///
/// The set of key codes that  is aware of. These represent physical keys
/// on the keyboard and are layout-independent. For example, the "a" key on a US
/// keyboard is the same as the "ф" key on a Russian keyboard, but both will
/// report the same key_a value.
///
/// Layout-dependent strings are provided separately as UTF-8 text and are produced
/// by the platform. These values are based on the W3C UI Events KeyboardEvent code
/// standard. See: https://www.w3.org/TR/uievents-code
///
/// @ingroup key
enum Key {
  unidentified(0),
  backquote(1),
  backslash(2),
  bracketLeft(3),
  bracketRight(4),
  comma(5),
  digit0(6),
  digit1(7),
  digit2(8),
  digit3(9),
  digit4(10),
  digit5(11),
  digit6(12),
  digit7(13),
  digit8(14),
  digit9(15),
  equal(16),
  intlBackslash(17),
  intlRo(18),
  intlYen(19),
  a(20),
  b(21),
  c(22),
  d(23),
  e(24),
  f(25),
  g(26),
  h(27),
  i(28),
  j(29),
  k(30),
  l(31),
  m(32),
  n(33),
  o(34),
  p(35),
  q(36),
  r(37),
  s(38),
  t(39),
  u(40),
  v(41),
  w(42),
  x(43),
  y(44),
  z(45),
  minus(46),
  period(47),
  quote(48),
  semicolon(49),
  slash(50),
  altLeft(51),
  altRight(52),
  backspace(53),
  capsLock(54),
  contextMenu(55),
  controlLeft(56),
  controlRight(57),
  enter(58),
  metaLeft(59),
  metaRight(60),
  shiftLeft(61),
  shiftRight(62),
  space(63),
  tab(64),
  convert(65),
  kanaMode(66),
  nonConvert(67),
  delete(68),
  end(69),
  help(70),
  home(71),
  insert(72),
  pageDown(73),
  pageUp(74),
  arrowDown(75),
  arrowLeft(76),
  arrowRight(77),
  arrowUp(78),
  numLock(79),
  numpad0(80),
  numpad1(81),
  numpad2(82),
  numpad3(83),
  numpad4(84),
  numpad5(85),
  numpad6(86),
  numpad7(87),
  numpad8(88),
  numpad9(89),
  numpadAdd(90),
  numpadBackspace(91),
  numpadClear(92),
  numpadClearEntry(93),
  numpadComma(94),
  numpadDecimal(95),
  numpadDivide(96),
  numpadEnter(97),
  numpadEqual(98),
  numpadMemoryAdd(99),
  numpadMemoryClear(100),
  numpadMemoryRecall(101),
  numpadMemoryStore(102),
  numpadMemorySubtract(103),
  numpadMultiply(104),
  numpadParenLeft(105),
  numpadParenRight(106),
  numpadSubtract(107),
  numpadSeparator(108),
  numpadUp(109),
  numpadDown(110),
  numpadRight(111),
  numpadLeft(112),
  numpadBegin(113),
  numpadHome(114),
  numpadEnd(115),
  numpadInsert(116),
  numpadDelete(117),
  numpadPageUp(118),
  numpadPageDown(119),
  escape(120),
  f1(121),
  f2(122),
  f3(123),
  f4(124),
  f5(125),
  f6(126),
  f7(127),
  f8(128),
  f9(129),
  f10(130),
  f11(131),
  f12(132),
  f13(133),
  f14(134),
  f15(135),
  f16(136),
  f17(137),
  f18(138),
  f19(139),
  f20(140),
  f21(141),
  f22(142),
  f23(143),
  f24(144),
  f25(145),
  fn(146),
  fnLock(147),
  printScreen(148),
  scrollLock(149),
  pause(150),
  browserBack(151),
  browserFavorites(152),
  browserForward(153),
  browserHome(154),
  browserRefresh(155),
  browserSearch(156),
  browserStop(157),
  eject(158),
  launchApp1(159),
  launchApp2(160),
  launchMail(161),
  mediaPlayPause(162),
  mediaSelect(163),
  mediaStop(164),
  mediaTrackNext(165),
  mediaTrackPrevious(166),
  power(167),
  sleep(168),
  audioVolumeDown(169),
  audioVolumeMute(170),
  audioVolumeUp(171),
  wakeUp(172),
  copy(173),
  cut(174),
  paste(175);

  final int value;
  const Key(this.value);

  static Key fromValue(int value) => switch (value) {
    0 => unidentified,
    1 => backquote,
    2 => backslash,
    3 => bracketLeft,
    4 => bracketRight,
    5 => comma,
    6 => digit0,
    7 => digit1,
    8 => digit2,
    9 => digit3,
    10 => digit4,
    11 => digit5,
    12 => digit6,
    13 => digit7,
    14 => digit8,
    15 => digit9,
    16 => equal,
    17 => intlBackslash,
    18 => intlRo,
    19 => intlYen,
    20 => a,
    21 => b,
    22 => c,
    23 => d,
    24 => e,
    25 => f,
    26 => g,
    27 => h,
    28 => i,
    29 => j,
    30 => k,
    31 => l,
    32 => m,
    33 => n,
    34 => o,
    35 => p,
    36 => q,
    37 => r,
    38 => s,
    39 => t,
    40 => u,
    41 => v,
    42 => w,
    43 => x,
    44 => y,
    45 => z,
    46 => minus,
    47 => period,
    48 => quote,
    49 => semicolon,
    50 => slash,
    51 => altLeft,
    52 => altRight,
    53 => backspace,
    54 => capsLock,
    55 => contextMenu,
    56 => controlLeft,
    57 => controlRight,
    58 => enter,
    59 => metaLeft,
    60 => metaRight,
    61 => shiftLeft,
    62 => shiftRight,
    63 => space,
    64 => tab,
    65 => convert,
    66 => kanaMode,
    67 => nonConvert,
    68 => delete,
    69 => end,
    70 => help,
    71 => home,
    72 => insert,
    73 => pageDown,
    74 => pageUp,
    75 => arrowDown,
    76 => arrowLeft,
    77 => arrowRight,
    78 => arrowUp,
    79 => numLock,
    80 => numpad0,
    81 => numpad1,
    82 => numpad2,
    83 => numpad3,
    84 => numpad4,
    85 => numpad5,
    86 => numpad6,
    87 => numpad7,
    88 => numpad8,
    89 => numpad9,
    90 => numpadAdd,
    91 => numpadBackspace,
    92 => numpadClear,
    93 => numpadClearEntry,
    94 => numpadComma,
    95 => numpadDecimal,
    96 => numpadDivide,
    97 => numpadEnter,
    98 => numpadEqual,
    99 => numpadMemoryAdd,
    100 => numpadMemoryClear,
    101 => numpadMemoryRecall,
    102 => numpadMemoryStore,
    103 => numpadMemorySubtract,
    104 => numpadMultiply,
    105 => numpadParenLeft,
    106 => numpadParenRight,
    107 => numpadSubtract,
    108 => numpadSeparator,
    109 => numpadUp,
    110 => numpadDown,
    111 => numpadRight,
    112 => numpadLeft,
    113 => numpadBegin,
    114 => numpadHome,
    115 => numpadEnd,
    116 => numpadInsert,
    117 => numpadDelete,
    118 => numpadPageUp,
    119 => numpadPageDown,
    120 => escape,
    121 => f1,
    122 => f2,
    123 => f3,
    124 => f4,
    125 => f5,
    126 => f6,
    127 => f7,
    128 => f8,
    129 => f9,
    130 => f10,
    131 => f11,
    132 => f12,
    133 => f13,
    134 => f14,
    135 => f15,
    136 => f16,
    137 => f17,
    138 => f18,
    139 => f19,
    140 => f20,
    141 => f21,
    142 => f22,
    143 => f23,
    144 => f24,
    145 => f25,
    146 => fn,
    147 => fnLock,
    148 => printScreen,
    149 => scrollLock,
    150 => pause,
    151 => browserBack,
    152 => browserFavorites,
    153 => browserForward,
    154 => browserHome,
    155 => browserRefresh,
    156 => browserSearch,
    157 => browserStop,
    158 => eject,
    159 => launchApp1,
    160 => launchApp2,
    161 => launchMail,
    162 => mediaPlayPause,
    163 => mediaSelect,
    164 => mediaStop,
    165 => mediaTrackNext,
    166 => mediaTrackPrevious,
    167 => power,
    168 => sleep,
    169 => audioVolumeDown,
    170 => audioVolumeMute,
    171 => audioVolumeUp,
    172 => wakeUp,
    173 => copy,
    174 => cut,
    175 => paste,
    _ => throw ArgumentError('Unknown value for Key: $value'),
  };
}

/// Keyboard input event types.
///
/// @ingroup key
enum KeyAction {
  /// Key was released
  release(0),

  /// Key was pressed
  press(1),

  /// Key is being repeated (held down)
  repeat(2);

  final int value;
  const KeyAction(this.value);

  static KeyAction fromValue(int value) => switch (value) {
    0 => release,
    1 => press,
    2 => repeat,
    _ => throw ArgumentError('Unknown value for KeyAction: $value'),
  };
}

/// Key encoder option identifiers.
///
/// These values are used with ghostty_key_encoder_setopt() to configure
/// the behavior of the key encoder.
///
/// @ingroup key
enum KeyEncoderOption {
  /// Terminal DEC mode 1: cursor key application mode (value: bool)
  cursorKeyApplication(0),

  /// Terminal DEC mode 66: keypad key application mode (value: bool)
  keypadKeyApplication(1),

  /// Terminal DEC mode 1035: ignore keypad with numlock (value: bool)
  ignoreKeypadWithNumlock(2),

  /// Terminal DEC mode 1036: alt sends escape prefix (value: bool)
  altEscPrefix(3),

  /// xterm modifyOtherKeys mode 2 (value: bool)
  modifyOtherKeysState2(4),

  /// Kitty keyboard protocol flags (value: KittyKeyFlags bitmask)
  kittyFlags(5),

  /// macOS option-as-alt setting (value: OptionAsAlt)
  macosOptionAsAlt(6),

  /// Backarrow key mode (value: bool)
  /// See https://vt100.net/dec/ek-vt3xx-tp-002.pdf page 170
  /// If `false` (the default), `backspace` emits 0x7f
  /// If `true`, `backspace` emits 0x08
  backarrowKeyMode(7);

  final int value;
  const KeyEncoderOption(this.value);

  static KeyEncoderOption fromValue(int value) => switch (value) {
    0 => cursorKeyApplication,
    1 => keypadKeyApplication,
    2 => ignoreKeypadWithNumlock,
    3 => altEscPrefix,
    4 => modifyOtherKeysState2,
    5 => kittyFlags,
    6 => macosOptionAsAlt,
    7 => backarrowKeyMode,
    _ => throw ArgumentError('Unknown value for KeyEncoderOption: $value'),
  };
}

/// Queryable data kinds for ghostty_kitty_graphics_get().
///
/// @ingroup kitty_graphics
enum KittyGraphicsData {
  /// Invalid / sentinel value.
  invalid(0),

  /// Populate a pre-allocated placement iterator with placement data from
  /// the storage. Iterator data is only valid as long as the underlying
  /// terminal is not mutated.
  ///
  /// Output type: KittyGraphicsPlacementIterator *
  placementIterator(1);

  final int value;
  const KittyGraphicsData(this.value);

  static KittyGraphicsData fromValue(int value) => switch (value) {
    0 => invalid,
    1 => placementIterator,
    _ => throw ArgumentError('Unknown value for KittyGraphicsData: $value'),
  };
}

/// Queryable data kinds for ghostty_kitty_graphics_image_get().
///
/// @ingroup kitty_graphics
enum KittyGraphicsImageData {
  /// Invalid / sentinel value.
  invalid(0),

  /// The image ID.
  ///
  /// Output type: uint32_t *
  id(1),

  /// The image number.
  ///
  /// Output type: uint32_t *
  number(2),

  /// Image width in pixels.
  ///
  /// Output type: uint32_t *
  width(3),

  /// Image height in pixels.
  ///
  /// Output type: uint32_t *
  height(4),

  /// Pixel format of the image.
  ///
  /// Output type: KittyImageFormat *
  format(5),

  /// Compression of the image.
  ///
  /// Output type: KittyImageCompression *
  compression(6),

  /// Borrowed pointer to the raw pixel data. Valid as long as the
  /// underlying terminal is not mutated.
  ///
  /// Output type: const uint8_t **
  dataPtr(7),

  /// Length of the raw pixel data in bytes.
  ///
  /// Output type: size_t *
  dataLen(8);

  final int value;
  const KittyGraphicsImageData(this.value);

  static KittyGraphicsImageData fromValue(int value) => switch (value) {
    0 => invalid,
    1 => id,
    2 => number,
    3 => width,
    4 => height,
    5 => format,
    6 => compression,
    7 => dataPtr,
    8 => dataLen,
    _ => throw ArgumentError(
      'Unknown value for KittyGraphicsImageData: $value',
    ),
  };
}

/// Queryable data kinds for ghostty_kitty_graphics_placement_get().
///
/// @ingroup kitty_graphics
enum KittyGraphicsPlacementData {
  /// Invalid / sentinel value.
  invalid(0),

  /// The image ID this placement belongs to.
  ///
  /// Output type: uint32_t *
  imageId(1),

  /// The placement ID.
  ///
  /// Output type: uint32_t *
  placementId(2),

  /// Whether this is a virtual placement (unicode placeholder).
  ///
  /// Output type: bool *
  isVirtual(3),

  /// Pixel offset from the left edge of the cell.
  ///
  /// Output type: uint32_t *
  xOffset(4),

  /// Pixel offset from the top edge of the cell.
  ///
  /// Output type: uint32_t *
  yOffset(5),

  /// Source rectangle x origin in pixels.
  ///
  /// Output type: uint32_t *
  sourceX(6),

  /// Source rectangle y origin in pixels.
  ///
  /// Output type: uint32_t *
  sourceY(7),

  /// Source rectangle width in pixels (0 = full image width).
  ///
  /// Output type: uint32_t *
  sourceWidth(8),

  /// Source rectangle height in pixels (0 = full image height).
  ///
  /// Output type: uint32_t *
  sourceHeight(9),

  /// Number of columns this placement occupies.
  ///
  /// Output type: uint32_t *
  columns(10),

  /// Number of rows this placement occupies.
  ///
  /// Output type: uint32_t *
  rows(11),

  /// Z-index for this placement.
  ///
  /// Output type: int32_t *
  z(12);

  final int value;
  const KittyGraphicsPlacementData(this.value);

  static KittyGraphicsPlacementData fromValue(int value) => switch (value) {
    0 => invalid,
    1 => imageId,
    2 => placementId,
    3 => isVirtual,
    4 => xOffset,
    5 => yOffset,
    6 => sourceX,
    7 => sourceY,
    8 => sourceWidth,
    9 => sourceHeight,
    10 => columns,
    11 => rows,
    12 => z,
    _ => throw ArgumentError(
      'Unknown value for KittyGraphicsPlacementData: $value',
    ),
  };
}

/// Settable options for ghostty_kitty_graphics_placement_iterator_set().
///
/// @ingroup kitty_graphics
enum KittyGraphicsPlacementIteratorOption {
  /// Set the z-layer filter for the iterator.
  ///
  /// Input type: KittyPlacementLayer *
  layer(0);

  final int value;
  const KittyGraphicsPlacementIteratorOption(this.value);

  static KittyGraphicsPlacementIteratorOption fromValue(int value) =>
      switch (value) {
        0 => layer,
        _ => throw ArgumentError(
          'Unknown value for KittyGraphicsPlacementIteratorOption: $value',
        ),
      };
}

/// Compression of a Kitty graphics image.
///
/// @ingroup kitty_graphics
enum KittyImageCompression {
  none(0),
  zlibDeflate(1);

  final int value;
  const KittyImageCompression(this.value);

  static KittyImageCompression fromValue(int value) => switch (value) {
    0 => none,
    1 => zlibDeflate,
    _ => throw ArgumentError('Unknown value for KittyImageCompression: $value'),
  };
}

/// Pixel format of a Kitty graphics image.
///
/// @ingroup kitty_graphics
enum KittyImageFormat {
  rgb(0),
  rgba(1),
  png(2),
  grayAlpha(3),
  gray(4);

  final int value;
  const KittyImageFormat(this.value);

  static KittyImageFormat fromValue(int value) => switch (value) {
    0 => rgb,
    1 => rgba,
    2 => png,
    3 => grayAlpha,
    4 => gray,
    _ => throw ArgumentError('Unknown value for KittyImageFormat: $value'),
  };
}

/// Z-layer classification for kitty graphics placements.
///
/// Based on the kitty protocol z-index conventions:
/// - BELOW_BG:   z < INT32_MIN/2  (drawn below cell background)
/// - BELOW_TEXT:  INT32_MIN/2 <= z < 0  (above background, below text)
/// - ABOVE_TEXT:  z >= 0  (above text)
/// - ALL:         no filtering (current behavior)
///
/// @ingroup kitty_graphics
enum KittyPlacementLayer {
  all(0),
  belowBg(1),
  belowText(2),
  aboveText(3);

  final int value;
  const KittyPlacementLayer(this.value);

  static KittyPlacementLayer fromValue(int value) => switch (value) {
    0 => all,
    1 => belowBg,
    2 => belowText,
    3 => aboveText,
    _ => throw ArgumentError('Unknown value for KittyPlacementLayer: $value'),
  };
}

/// DECRPM report state values.
///
/// These correspond to the Ps2 parameter in a DECRPM response
/// sequence (CSI ? Ps1 ; Ps2 $ y).
enum ModeReportState {
  /// Mode is not recognized
  notRecognized(0),

  /// Mode is set (enabled)
  set(1),

  /// Mode is reset (disabled)
  reset(2),

  /// Mode is permanently set
  permanentlySet(3),

  /// Mode is permanently reset
  permanentlyReset(4);

  final int value;
  const ModeReportState(this.value);

  static ModeReportState fromValue(int value) => switch (value) {
    0 => notRecognized,
    1 => set,
    2 => reset,
    3 => permanentlySet,
    4 => permanentlyReset,
    _ => throw ArgumentError('Unknown value for ModeReportState: $value'),
  };
}

/// Mouse event action type.
///
/// @ingroup mouse
enum MouseAction {
  /// Mouse button was pressed.
  press(0),

  /// Mouse button was released.
  release(1),

  /// Mouse moved.
  motion(2);

  final int value;
  const MouseAction(this.value);

  static MouseAction fromValue(int value) => switch (value) {
    0 => press,
    1 => release,
    2 => motion,
    _ => throw ArgumentError('Unknown value for MouseAction: $value'),
  };
}

/// Mouse button identity.
///
/// @ingroup mouse
enum MouseButton {
  unknown(0),
  left(1),
  right(2),
  middle(3),
  four(4),
  five(5),
  six(6),
  seven(7),
  eight(8),
  nine(9),
  ten(10),
  eleven(11);

  final int value;
  const MouseButton(this.value);

  static MouseButton fromValue(int value) => switch (value) {
    0 => unknown,
    1 => left,
    2 => right,
    3 => middle,
    4 => four,
    5 => five,
    6 => six,
    7 => seven,
    8 => eight,
    9 => nine,
    10 => ten,
    11 => eleven,
    _ => throw ArgumentError('Unknown value for MouseButton: $value'),
  };
}

/// Mouse encoder option identifiers.
///
/// These values are used with ghostty_mouse_encoder_setopt() to configure
/// the behavior of the mouse encoder.
///
/// @ingroup mouse
enum MouseEncoderOption {
  /// Mouse tracking mode (value: MouseTrackingMode).
  event(0),

  /// Mouse output format (value: MouseFormat).
  format(1),

  /// Renderer size context (value: MouseEncoderSize).
  size(2),

  /// Whether any mouse button is currently pressed (value: bool).
  anyButtonPressed(3),

  /// Whether to enable motion deduplication by last cell (value: bool).
  trackLastCell(4);

  final int value;
  const MouseEncoderOption(this.value);

  static MouseEncoderOption fromValue(int value) => switch (value) {
    0 => event,
    1 => format,
    2 => size,
    3 => anyButtonPressed,
    4 => trackLastCell,
    _ => throw ArgumentError('Unknown value for MouseEncoderOption: $value'),
  };
}

/// Mouse output format.
///
/// @ingroup mouse
enum MouseFormat {
  x10(0),
  utf8(1),
  sgr(2),
  urxvt(3),
  sgrPixels(4);

  final int value;
  const MouseFormat(this.value);

  static MouseFormat fromValue(int value) => switch (value) {
    0 => x10,
    1 => utf8,
    2 => sgr,
    3 => urxvt,
    4 => sgrPixels,
    _ => throw ArgumentError('Unknown value for MouseFormat: $value'),
  };
}

/// Mouse tracking mode.
///
/// @ingroup mouse
enum MouseTrackingMode {
  /// Mouse reporting disabled.
  none(0),

  /// X10 mouse mode.
  x10(1),

  /// Normal mouse mode (button press/release only).
  normal(2),

  /// Button-event tracking mode.
  button(3),

  /// Any-event tracking mode.
  any(4);

  final int value;
  const MouseTrackingMode(this.value);

  static MouseTrackingMode fromValue(int value) => switch (value) {
    0 => none,
    1 => x10,
    2 => normal,
    3 => button,
    4 => any,
    _ => throw ArgumentError('Unknown value for MouseTrackingMode: $value'),
  };
}

/// Build optimization mode.
enum OptimizeMode {
  debug(0),
  releaseSafe(1),
  releaseSmall(2),
  releaseFast(3);

  final int value;
  const OptimizeMode(this.value);

  static OptimizeMode fromValue(int value) => switch (value) {
    0 => debug,
    1 => releaseSafe,
    2 => releaseSmall,
    3 => releaseFast,
    _ => throw ArgumentError('Unknown value for OptimizeMode: $value'),
  };
}

/// macOS option key behavior.
///
/// Determines whether the "option" key on macOS is treated as "alt" or not.
/// See the  `macos-option-as-alt` configuration option for more details.
///
/// @ingroup key
enum OptionAsAlt {
  /// Option key is not treated as alt
  false$(0),

  /// Option key is treated as alt
  true$(1),

  /// Only left option key is treated as alt
  left(2),

  /// Only right option key is treated as alt
  right(3);

  final int value;
  const OptionAsAlt(this.value);

  static OptionAsAlt fromValue(int value) => switch (value) {
    0 => false$,
    1 => true$,
    2 => left,
    3 => right,
    _ => throw ArgumentError('Unknown value for OptionAsAlt: $value'),
  };
}

/// OSC command data types.
///
/// These values specify what type of data to extract from an OSC command
/// using `ghostty_osc_command_data`.
///
/// @ingroup osc
enum OscCommandData {
  /// Invalid data type. Never results in any data extraction.
  invalid(0),

  /// Window title string data.
  ///
  /// Valid for: GHOSTTY_OSC_COMMAND_CHANGE_WINDOW_TITLE
  ///
  /// Output type: const char ** (pointer to null-terminated string)
  ///
  /// Lifetime: Valid until the next call to any ghostty_osc_* function with
  /// the same parser instance. Memory is owned by the parser.
  changeWindowTitleStr(1);

  final int value;
  const OscCommandData(this.value);

  static OscCommandData fromValue(int value) => switch (value) {
    0 => invalid,
    1 => changeWindowTitleStr,
    _ => throw ArgumentError('Unknown value for OscCommandData: $value'),
  };
}

/// OSC command types.
///
/// @ingroup osc
enum OscCommandType {
  invalid(0),
  changeWindowTitle(1),
  changeWindowIcon(2),
  semanticPrompt(3),
  clipboardContents(4),
  reportPwd(5),
  mouseShape(6),
  colorOperation(7),
  kittyColorProtocol(8),
  showDesktopNotification(9),
  hyperlinkStart(10),
  hyperlinkEnd(11),
  conemuSleep(12),
  conemuShowMessageBox(13),
  conemuChangeTabTitle(14),
  conemuProgressReport(15),
  conemuWaitInput(16),
  conemuGuimacro(17),
  conemuRunProcess(18),
  conemuOutputEnvironmentVariable(19),
  conemuXtermEmulation(20),
  conemuComment(21),
  kittyTextSizing(22);

  final int value;
  const OscCommandType(this.value);

  static OscCommandType fromValue(int value) => switch (value) {
    0 => invalid,
    1 => changeWindowTitle,
    2 => changeWindowIcon,
    3 => semanticPrompt,
    4 => clipboardContents,
    5 => reportPwd,
    6 => mouseShape,
    7 => colorOperation,
    8 => kittyColorProtocol,
    9 => showDesktopNotification,
    10 => hyperlinkStart,
    11 => hyperlinkEnd,
    12 => conemuSleep,
    13 => conemuShowMessageBox,
    14 => conemuChangeTabTitle,
    15 => conemuProgressReport,
    16 => conemuWaitInput,
    17 => conemuGuimacro,
    18 => conemuRunProcess,
    19 => conemuOutputEnvironmentVariable,
    20 => conemuXtermEmulation,
    21 => conemuComment,
    22 => kittyTextSizing,
    _ => throw ArgumentError('Unknown value for OscCommandType: $value'),
  };
}

/// Point reference tag.
///
/// Determines which coordinate system a point uses.
///
/// @ingroup point
enum PointTag {
  /// Active area where the cursor can move.
  active(0),

  /// Visible viewport (changes when scrolled).
  viewport(1),

  /// Full screen including scrollback.
  screen(2),

  /// Scrollback history only (before active area).
  history(3);

  final int value;
  const PointTag(this.value);

  static PointTag fromValue(int value) => switch (value) {
    0 => active,
    1 => viewport,
    2 => screen,
    3 => history,
    _ => throw ArgumentError('Unknown value for PointTag: $value'),
  };
}

/// Visual style of the cursor.
///
/// @ingroup render
enum RenderStateCursorVisualStyle {
  /// Bar cursor (DECSCUSR 5, 6).
  bar(0),

  /// Block cursor (DECSCUSR 1, 2).
  block(1),

  /// Underline cursor (DECSCUSR 3, 4).
  underline(2),

  /// Hollow block cursor.
  blockHollow(3);

  final int value;
  const RenderStateCursorVisualStyle(this.value);

  static RenderStateCursorVisualStyle fromValue(int value) => switch (value) {
    0 => bar,
    1 => block,
    2 => underline,
    3 => blockHollow,
    _ => throw ArgumentError(
      'Unknown value for RenderStateCursorVisualStyle: $value',
    ),
  };
}

/// Queryable data kinds for ghostty_render_state_get().
///
/// @ingroup render
enum RenderStateData {
  /// Invalid / sentinel value.
  invalid(0),

  /// Viewport width in cells (uint16_t).
  cols(1),

  /// Viewport height in cells (uint16_t).
  rows(2),

  /// Current dirty state (RenderStateDirty).
  dirty(3),

  /// Populate a pre-allocated RenderStateRowIterator with row data
  /// from the render state (RenderStateRowIterator). Row data is
  /// only valid as long as the underlying render state is not updated.
  /// It is unsafe to use row data after updating the render state.
  rowIterator(4),

  /// Default/current background color (ColorRgb).
  colorBackground(5),

  /// Default/current foreground color (ColorRgb).
  colorForeground(6),

  /// Cursor color when explicitly set by terminal state (ColorRgb).
  /// Returns GHOSTTY_INVALID_VALUE if no explicit cursor color is set;
  /// use COLOR_CURSOR_HAS_VALUE to check first.
  colorCursor(7),

  /// Whether an explicit cursor color is set (bool).
  colorCursorHasValue(8),

  /// The active 256-color palette (ColorRgb[256]).
  colorPalette(9),

  /// The visual style of the cursor (RenderStateCursorVisualStyle).
  cursorVisualStyle(10),

  /// Whether the cursor is visible based on terminal modes (bool).
  cursorVisible(11),

  /// Whether the cursor should blink based on terminal modes (bool).
  cursorBlinking(12),

  /// Whether the cursor is at a password input field (bool).
  cursorPasswordInput(13),

  /// Whether the cursor is visible within the viewport (bool).
  /// If false, the cursor viewport position values are undefined.
  cursorViewportHasValue(14),

  /// Cursor viewport x position in cells (uint16_t).
  /// Only valid when CURSOR_VIEWPORT_HAS_VALUE is true.
  cursorViewportX(15),

  /// Cursor viewport y position in cells (uint16_t).
  /// Only valid when CURSOR_VIEWPORT_HAS_VALUE is true.
  cursorViewportY(16),

  /// Whether the cursor is on the tail of a wide character (bool).
  /// Only valid when CURSOR_VIEWPORT_HAS_VALUE is true.
  cursorViewportWideTail(17);

  final int value;
  const RenderStateData(this.value);

  static RenderStateData fromValue(int value) => switch (value) {
    0 => invalid,
    1 => cols,
    2 => rows,
    3 => dirty,
    4 => rowIterator,
    5 => colorBackground,
    6 => colorForeground,
    7 => colorCursor,
    8 => colorCursorHasValue,
    9 => colorPalette,
    10 => cursorVisualStyle,
    11 => cursorVisible,
    12 => cursorBlinking,
    13 => cursorPasswordInput,
    14 => cursorViewportHasValue,
    15 => cursorViewportX,
    16 => cursorViewportY,
    17 => cursorViewportWideTail,
    _ => throw ArgumentError('Unknown value for RenderStateData: $value'),
  };
}

/// Dirty state of a render state after update.
///
/// @ingroup render
enum RenderStateDirty {
  /// Not dirty at all; rendering can be skipped.
  false$(0),

  /// Some rows changed; renderer can redraw incrementally.
  partial(1),

  /// Global state changed; renderer should redraw everything.
  full(2);

  final int value;
  const RenderStateDirty(this.value);

  static RenderStateDirty fromValue(int value) => switch (value) {
    0 => false$,
    1 => partial,
    2 => full,
    _ => throw ArgumentError('Unknown value for RenderStateDirty: $value'),
  };
}

/// Settable options for ghostty_render_state_set().
///
/// @ingroup render
enum RenderStateOption {
  /// Set dirty state (RenderStateDirty).
  dirty(0);

  final int value;
  const RenderStateOption(this.value);

  static RenderStateOption fromValue(int value) => switch (value) {
    0 => dirty,
    _ => throw ArgumentError('Unknown value for RenderStateOption: $value'),
  };
}

/// Queryable data kinds for ghostty_render_state_row_cells_get().
///
/// @ingroup render
enum RenderStateRowCellsData {
  /// Invalid / sentinel value.
  invalid(0),

  /// The raw cell value (Cell).
  raw(1),

  /// The style for the current cell (Style).
  style(2),

  /// The total number of grapheme codepoints including the base codepoint
  /// (uint32_t). Returns 0 if the cell has no text.
  graphemesLen(3),

  /// Write grapheme codepoints into a caller-provided buffer (uint32_t*).
  /// The buffer must be at least graphemes_len elements. The base codepoint
  /// is written first, followed by any extra codepoints.
  graphemesBuf(4),

  /// The resolved background color of the cell (ColorRgb).
  /// Flattens the three possible sources: content-tag bg_color_rgb,
  /// content-tag bg_color_palette (looked up in the palette), or the
  /// style's bg_color. Returns GHOSTTY_INVALID_VALUE if the cell has
  /// no background color, in which case the caller should use whatever
  /// default background color it wants (e.g. the terminal background).
  bgColor(5),

  /// The resolved foreground color of the cell (ColorRgb).
  /// Resolves palette indices through the palette. Bold color handling
  /// is not applied; the caller should handle bold styling separately.
  /// Returns GHOSTTY_INVALID_VALUE if the cell has no explicit foreground
  /// color, in which case the caller should use whatever default foreground
  /// color it wants (e.g. the terminal foreground).
  fgColor(6),

  /// Whether the cell is contained within the current selection (bool).
  /// This returns true when the cell's column is within the current row's
  /// row-local selection range, and false otherwise. Rendering policy for
  /// selected cells (colors, inversion, etc.) is left to the caller.
  ///
  /// Renderers that can draw cells in spans may be more efficient querying
  /// GHOSTTY_RENDER_STATE_ROW_DATA_SELECTION once per row and applying that
  /// range directly, avoiding one C API call per cell for selection state.
  selected(7),

  /// Whether the cell has any explicit styling (bool).
  /// This is equivalent to querying the raw cell's
  /// GHOSTTY_CELL_DATA_HAS_STYLING value, but avoids materializing the raw
  /// Cell for renderers that only need to know whether fetching the
  /// full style is necessary.
  hasStyling(8),

  /// Encode the current cell's full grapheme cluster as UTF-8 into a
  /// caller-provided buffer (Buffer).
  ///
  /// The base codepoint is encoded first, followed by any extra grapheme
  /// codepoints. Returns GHOSTTY_SUCCESS with len=0 when the cell has no text.
  ///
  /// If ptr is NULL or cap is too small for a non-empty cell, returns
  /// GHOSTTY_OUT_OF_SPACE without writing any bytes and sets len to the required
  /// buffer size in bytes.
  graphemesUtf8(9);

  final int value;
  const RenderStateRowCellsData(this.value);

  static RenderStateRowCellsData fromValue(int value) => switch (value) {
    0 => invalid,
    1 => raw,
    2 => style,
    3 => graphemesLen,
    4 => graphemesBuf,
    5 => bgColor,
    6 => fgColor,
    7 => selected,
    8 => hasStyling,
    9 => graphemesUtf8,
    _ => throw ArgumentError(
      'Unknown value for RenderStateRowCellsData: $value',
    ),
  };
}

/// Queryable data kinds for ghostty_render_state_row_get().
///
/// @ingroup render
enum RenderStateRowData {
  /// Invalid / sentinel value.
  invalid(0),

  /// Whether the current row is dirty (bool).
  dirty(1),

  /// The raw row value (Row).
  raw(2),

  /// Populate a pre-allocated RenderStateRowCells with cell data for
  /// the current row (RenderStateRowCells). Cell data is only
  /// valid as long as the underlying render state is not updated.
  /// It is unsafe to use cell data after updating the render state.
  cells(3),

  /// Row-local selected cell range (RenderStateRowSelection).
  selection(4);

  final int value;
  const RenderStateRowData(this.value);

  static RenderStateRowData fromValue(int value) => switch (value) {
    0 => invalid,
    1 => dirty,
    2 => raw,
    3 => cells,
    4 => selection,
    _ => throw ArgumentError('Unknown value for RenderStateRowData: $value'),
  };
}

/// Settable options for ghostty_render_state_row_set().
///
/// @ingroup render
enum RenderStateRowOption {
  /// Set dirty state for the current row (bool).
  dirty(0);

  final int value;
  const RenderStateRowOption(this.value);

  static RenderStateRowOption fromValue(int value) => switch (value) {
    0 => dirty,
    _ => throw ArgumentError('Unknown value for RenderStateRowOption: $value'),
  };
}

/// Result codes for libghostty-vt operations.
enum Result {
  /// Operation completed successfully
  success(0),

  /// Operation failed due to failed allocation
  outOfMemory(-1),

  /// Operation failed due to invalid value
  invalidValue(-2),

  /// Operation failed because the provided buffer was too small
  outOfSpace(-3),

  /// The requested value has no value
  noValue(-4);

  final int value;
  const Result(this.value);

  static Result fromValue(int value) => switch (value) {
    0 => success,
    -1 => outOfMemory,
    -2 => invalidValue,
    -3 => outOfSpace,
    -4 => noValue,
    _ => throw ArgumentError('Unknown value for Result: $value'),
  };
}

/// Row data types.
///
/// These values specify what type of data to extract from a row
/// using `ghostty_row_get`.
///
/// @ingroup screen
enum RowData {
  /// Invalid data type. Never results in any data extraction.
  invalid(0),

  /// Whether this row is soft-wrapped.
  ///
  /// Output type: bool *
  wrap(1),

  /// Whether this row is a continuation of a soft-wrapped row.
  ///
  /// Output type: bool *
  wrapContinuation(2),

  /// Whether any cells in this row have grapheme clusters.
  ///
  /// Output type: bool *
  grapheme(3),

  /// Whether any cells in this row have styling (may have false positives).
  ///
  /// Output type: bool *
  styled(4),

  /// Whether any cells in this row have hyperlinks (may have false positives).
  ///
  /// Output type: bool *
  hyperlink(5),

  /// The semantic prompt state of this row.
  ///
  /// Output type: RowSemanticPrompt *
  semanticPrompt(6),

  /// Whether this row contains a Kitty virtual placeholder.
  ///
  /// Output type: bool *
  kittyVirtualPlaceholder(7),

  /// Whether this row is dirty and requires a redraw.
  ///
  /// Output type: bool *
  dirty(8);

  final int value;
  const RowData(this.value);

  static RowData fromValue(int value) => switch (value) {
    0 => invalid,
    1 => wrap,
    2 => wrapContinuation,
    3 => grapheme,
    4 => styled,
    5 => hyperlink,
    6 => semanticPrompt,
    7 => kittyVirtualPlaceholder,
    8 => dirty,
    _ => throw ArgumentError('Unknown value for RowData: $value'),
  };
}

/// Row semantic prompt state.
///
/// Indicates whether any cells in a row are part of a shell prompt,
/// as reported by OSC 133 sequences.
///
/// @ingroup screen
enum RowSemanticPrompt {
  /// No prompt cells in this row.
  none(0),

  /// Prompt cells exist and this is a primary prompt line.
  prompt(1),

  /// Prompt cells exist and this is a continuation line.
  promptContinuation(2);

  final int value;
  const RowSemanticPrompt(this.value);

  static RowSemanticPrompt fromValue(int value) => switch (value) {
    0 => none,
    1 => prompt,
    2 => promptContinuation,
    _ => throw ArgumentError('Unknown value for RowSemanticPrompt: $value'),
  };
}

/// Operation used to adjust a selection endpoint.
///
/// Adjustment mutates the selection's logical end endpoint, not whichever
/// endpoint is visually bottom/right. This preserves keyboard and drag
/// behavior for both forward and reversed selections.
///
/// @ingroup selection
enum SelectionAdjust {
  /// Move left to the previous non-empty cell, wrapping upward.
  left(0),

  /// Move right to the next non-empty cell, wrapping downward.
  right(1),

  /// Move up one row at the current column, or to the beginning of the
  /// line if already at the top.
  up(2),

  /// Move down to the next non-blank row at the current column, or to the
  /// end of the line if none exists.
  down(3),

  /// Move to the top-left cell of the screen.
  home(4),

  /// Move to the right edge of the last non-blank row on the screen.
  end(5),

  /// Move up by one terminal page height, or to home if that would move
  /// past the top.
  pageUp(6),

  /// Move down by one terminal page height, or to end if that would move
  /// past the bottom.
  pageDown(7),

  /// Move to the left edge of the current line.
  beginningOfLine(8),

  /// Move to the right edge of the current line.
  endOfLine(9);

  final int value;
  const SelectionAdjust(this.value);

  static SelectionAdjust fromValue(int value) => switch (value) {
    0 => left,
    1 => right,
    2 => up,
    3 => down,
    4 => home,
    5 => end,
    6 => pageUp,
    7 => pageDown,
    8 => beginningOfLine,
    9 => endOfLine,
    _ => throw ArgumentError('Unknown value for SelectionAdjust: $value'),
  };
}

/// Current autoscroll direction for an active selection drag gesture.
///
/// @ingroup selection
enum SelectionGestureAutoscroll {
  /// No selection autoscroll is requested.
  none(0),

  /// Selection dragging should autoscroll the viewport upward.
  up(1),

  /// Selection dragging should autoscroll the viewport downward.
  down(2);

  final int value;
  const SelectionGestureAutoscroll(this.value);

  static SelectionGestureAutoscroll fromValue(int value) => switch (value) {
    0 => none,
    1 => up,
    2 => down,
    _ => throw ArgumentError(
      'Unknown value for SelectionGestureAutoscroll: $value',
    ),
  };
}

/// Selection behavior chosen for a gesture's click sequence.
///
/// @ingroup selection
enum SelectionGestureBehavior {
  /// Cell-granular drag selection.
  cell(0),

  /// Word selection on press and word-granular drag selection.
  word(1),

  /// Line selection on press and line-granular drag selection.
  line(2),

  /// Semantic command output selection on press and drag.
  output(3);

  final int value;
  const SelectionGestureBehavior(this.value);

  static SelectionGestureBehavior fromValue(int value) => switch (value) {
    0 => cell,
    1 => word,
    2 => line,
    3 => output,
    _ => throw ArgumentError(
      'Unknown value for SelectionGestureBehavior: $value',
    ),
  };
}

/// Data fields readable from a selection gesture with
/// ghostty_selection_gesture_get().
///
/// @ingroup selection
enum SelectionGestureData {
  /// Current click count: uint8_t*. 0 means inactive.
  clickCount(0),

  /// Whether the current/last left-click gesture has dragged: bool*.
  dragged(1),

  /// Current autoscroll request: SelectionGestureAutoscroll*.
  autoscroll(2),

  /// Current gesture behavior: SelectionGestureBehavior*.
  behavior(3),

  /// Current left-click anchor: GridRef*.
  ///
  /// Returns GHOSTTY_NO_VALUE if there is no valid active anchor. On success,
  /// writes an untracked GridRef snapshot with normal GhosttyGridRef
  /// lifetime rules.
  anchor(4);

  final int value;
  const SelectionGestureData(this.value);

  static SelectionGestureData fromValue(int value) => switch (value) {
    0 => clickCount,
    1 => dragged,
    2 => autoscroll,
    3 => behavior,
    4 => anchor,
    _ => throw ArgumentError('Unknown value for SelectionGestureData: $value'),
  };
}

/// Options stored on a reusable selection gesture event.
///
/// Passing NULL as the value to ghostty_selection_gesture_event_set() clears the
/// corresponding option.
///
/// @ingroup selection
enum SelectionGestureEventOption {
  /// Grid reference under the pointer: GridRef*.
  ///
  /// Required for PRESS and DRAG events. Optional for RELEASE events; when unset
  /// or cleared, release records that the pointer did not map to a valid cell.
  ref(0),

  /// Surface-space pointer position: SurfacePosition*.
  ///
  /// Valid for PRESS, DRAG, and AUTOSCROLL_TICK.
  position(1),

  /// Maximum repeat-click distance in pixels: double*.
  repeatDistance(2),

  /// Optional monotonic event time in nanoseconds: uint64_t*.
  ///
  /// If unset, press treats the event as untimed and only single-click behavior
  /// is available.
  timeNs(3),

  /// Maximum interval between repeat clicks in nanoseconds: uint64_t*.
  repeatIntervalNs(4),

  /// Word-boundary codepoints: Codepoints*.
  ///
  /// The codepoints are copied into event-owned storage when set. If unset,
  /// operations that need word boundaries use 's defaults.
  ///
  /// Valid for PRESS, DRAG, AUTOSCROLL_TICK, and DEEP_PRESS.
  wordBoundaryCodepoints(5),

  /// Selection behavior table: SelectionGestureBehaviors*.
  ///
  /// If unset, press uses the default behavior table: cell, word, line.
  behaviors(6),

  /// Whether a drag or autoscroll tick should produce a rectangular selection: bool*.
  rectangle(7),

  /// Drag display geometry: SelectionGestureGeometry*. Required for DRAG and AUTOSCROLL_TICK.
  geometry(8),

  /// Viewport coordinate for an autoscroll tick: PointCoordinate*. Required for AUTOSCROLL_TICK.
  viewport(9);

  final int value;
  const SelectionGestureEventOption(this.value);

  static SelectionGestureEventOption fromValue(int value) => switch (value) {
    0 => ref,
    1 => position,
    2 => repeatDistance,
    3 => timeNs,
    4 => repeatIntervalNs,
    5 => wordBoundaryCodepoints,
    6 => behaviors,
    7 => rectangle,
    8 => geometry,
    9 => viewport,
    _ => throw ArgumentError(
      'Unknown value for SelectionGestureEventOption: $value',
    ),
  };
}

/// Selection gesture event type.
///
/// The event type is fixed when the event is created. Each event type documents
/// which options are valid and which options are required by gesture operations.
///
/// @ingroup selection
enum SelectionGestureEventType {
  /// Press event for ghostty_selection_gesture_event().
  press(0),

  /// Release event for ghostty_selection_gesture_event().
  release(1),

  /// Drag event for ghostty_selection_gesture_event().
  drag(2),

  /// Autoscroll tick event for ghostty_selection_gesture_event().
  autoscrollTick(3),

  /// Deep press event for ghostty_selection_gesture_event().
  deepPress(4);

  final int value;
  const SelectionGestureEventType(this.value);

  static SelectionGestureEventType fromValue(int value) => switch (value) {
    0 => press,
    1 => release,
    2 => drag,
    3 => autoscrollTick,
    4 => deepPress,
    _ => throw ArgumentError(
      'Unknown value for SelectionGestureEventType: $value',
    ),
  };
}

/// Ordering of a selection's endpoints in terminal coordinates.
///
/// Mirrored orders are only produced by rectangular selections whose start
/// and end endpoints are on opposite diagonal corners that are not simple
/// top-left-to-bottom-right or bottom-right-to-top-left orderings.
///
/// @ingroup selection
enum SelectionOrder {
  /// Start is before end in top-left to bottom-right order.
  forward(0),

  /// End is before start in top-left to bottom-right order.
  reverse(1),

  /// Rectangular selection from top-right to bottom-left.
  mirroredForward(2),

  /// Rectangular selection from bottom-left to top-right.
  mirroredReverse(3);

  final int value;
  const SelectionOrder(this.value);

  static SelectionOrder fromValue(int value) => switch (value) {
    0 => forward,
    1 => reverse,
    2 => mirroredForward,
    3 => mirroredReverse,
    _ => throw ArgumentError('Unknown value for SelectionOrder: $value'),
  };
}

/// SGR attribute tags.
///
/// These values identify the type of an SGR attribute in a tagged union.
/// Use the tag to determine which field in the attribute value union to access.
///
/// @ingroup sgr
enum SgrAttributeTag {
  unset(0),
  unknown(1),
  bold(2),
  resetBold(3),
  italic(4),
  resetItalic(5),
  faint(6),
  underline(7),
  underlineColor(8),
  underlineColor256(9),
  resetUnderlineColor(10),
  overline(11),
  resetOverline(12),
  blink(13),
  resetBlink(14),
  inverse(15),
  resetInverse(16),
  invisible(17),
  resetInvisible(18),
  strikethrough(19),
  resetStrikethrough(20),
  directColorFg(21),
  directColorBg(22),
  bg8(23),
  fg8(24),
  resetFg(25),
  resetBg(26),
  brightBg8(27),
  brightFg8(28),
  bg256(29),
  fg256(30);

  final int value;
  const SgrAttributeTag(this.value);

  static SgrAttributeTag fromValue(int value) => switch (value) {
    0 => unset,
    1 => unknown,
    2 => bold,
    3 => resetBold,
    4 => italic,
    5 => resetItalic,
    6 => faint,
    7 => underline,
    8 => underlineColor,
    9 => underlineColor256,
    10 => resetUnderlineColor,
    11 => overline,
    12 => resetOverline,
    13 => blink,
    14 => resetBlink,
    15 => inverse,
    16 => resetInverse,
    17 => invisible,
    18 => resetInvisible,
    19 => strikethrough,
    20 => resetStrikethrough,
    21 => directColorFg,
    22 => directColorBg,
    23 => bg8,
    24 => fg8,
    25 => resetFg,
    26 => resetBg,
    27 => brightBg8,
    28 => brightFg8,
    29 => bg256,
    30 => fg256,
    _ => throw ArgumentError('Unknown value for SgrAttributeTag: $value'),
  };
}

/// Underline style types.
///
/// @ingroup sgr
enum SgrUnderline {
  none(0),
  single(1),
  double(2),
  curly(3),
  dotted(4),
  dashed(5);

  final int value;
  const SgrUnderline(this.value);

  static SgrUnderline fromValue(int value) => switch (value) {
    0 => none,
    1 => single,
    2 => double,
    3 => curly,
    4 => dotted,
    5 => dashed,
    _ => throw ArgumentError('Unknown value for SgrUnderline: $value'),
  };
}

/// Size report style.
///
/// Determines the output format for the terminal size report.
enum SizeReportStyle {
  /// In-band size report (mode 2048): ESC [ 48 ; rows ; cols ; height ; width t
  mode2048(0),

  /// XTWINOPS text area size in pixels: ESC [ 4 ; height ; width t
  csi14T(1),

  /// XTWINOPS cell size in pixels: ESC [ 6 ; height ; width t
  csi16T(2),

  /// XTWINOPS text area size in characters: ESC [ 8 ; rows ; cols t
  csi18T(3);

  final int value;
  const SizeReportStyle(this.value);

  static SizeReportStyle fromValue(int value) => switch (value) {
    0 => mode2048,
    1 => csi14T,
    2 => csi16T,
    3 => csi18T,
    _ => throw ArgumentError('Unknown value for SizeReportStyle: $value'),
  };
}

/// Style color tags.
///
/// These values identify the type of color in a style color.
/// Use the tag to determine which field in the color value union to access.
///
/// @ingroup style
enum StyleColorTag {
  none(0),
  palette(1),
  rgb(2);

  final int value;
  const StyleColorTag(this.value);

  static StyleColorTag fromValue(int value) => switch (value) {
    0 => none,
    1 => palette,
    2 => rgb,
    _ => throw ArgumentError('Unknown value for StyleColorTag: $value'),
  };
}

/// Log severity levels for the log callback.
enum SysLogLevel {
  error(0),
  warning(1),
  info(2),
  debug(3);

  final int value;
  const SysLogLevel(this.value);

  static SysLogLevel fromValue(int value) => switch (value) {
    0 => error,
    1 => warning,
    2 => info,
    3 => debug,
    _ => throw ArgumentError('Unknown value for SysLogLevel: $value'),
  };
}

/// System option identifiers for ghostty_sys_set().
enum SysOption {
  /// Set the userdata pointer passed to all sys callbacks.
  ///
  /// Input type: void* (or NULL)
  userdata(0),

  /// Set the PNG decode function.
  ///
  /// When set, the terminal can accept PNG images via the Kitty
  /// Graphics Protocol. When cleared (NULL value), PNG decoding is
  /// unsupported and PNG image data will be rejected.
  ///
  /// Input type: SysDecodePngFn (function pointer, or NULL)
  decodePng(1),

  /// Set the log callback.
  ///
  /// When set, internal library log messages are delivered to this
  /// callback. When cleared (NULL value), log messages are silently
  /// discarded.
  ///
  /// Use ghostty_sys_log_stderr as a convenience callback that
  /// writes formatted messages to stderr.
  ///
  /// Which log levels are emitted depends on the build mode of the
  /// library and is not configurable at runtime. Debug builds emit
  /// all levels (debug and above). Release builds emit info and
  /// above; debug-level messages are compiled out entirely and will
  /// never reach the callback.
  ///
  /// Input type: SysLogFn (function pointer, or NULL)
  log(2);

  final int value;
  const SysOption(this.value);

  static SysOption fromValue(int value) => switch (value) {
    0 => userdata,
    1 => decodePng,
    2 => log,
    _ => throw ArgumentError('Unknown value for SysOption: $value'),
  };
}

/// Visual style of the terminal cursor.
///
/// @ingroup terminal
enum TerminalCursorStyle {
  /// Bar cursor (DECSCUSR 5, 6).
  bar(0),

  /// Block cursor (DECSCUSR 1, 2).
  block(1),

  /// Underline cursor (DECSCUSR 3, 4).
  underline(2),

  /// Hollow block cursor.
  blockHollow(3);

  final int value;
  const TerminalCursorStyle(this.value);

  static TerminalCursorStyle fromValue(int value) => switch (value) {
    0 => bar,
    1 => block,
    2 => underline,
    3 => blockHollow,
    _ => throw ArgumentError('Unknown value for TerminalCursorStyle: $value'),
  };
}

/// Terminal data types.
///
/// These values specify what type of data to extract from a terminal
/// using `ghostty_terminal_get`.
///
/// @ingroup terminal
enum TerminalData {
  /// Invalid data type. Never results in any data extraction.
  invalid(0),

  /// Terminal width in cells.
  ///
  /// Output type: uint16_t *
  cols(1),

  /// Terminal height in cells.
  ///
  /// Output type: uint16_t *
  rows(2),

  /// Cursor column position (0-indexed).
  ///
  /// Output type: uint16_t *
  cursorX(3),

  /// Cursor row position within the active area (0-indexed).
  ///
  /// Output type: uint16_t *
  cursorY(4),

  /// Whether the cursor has a pending wrap (next print will soft-wrap).
  ///
  /// Output type: bool *
  cursorPendingWrap(5),

  /// The currently active screen.
  ///
  /// Output type: TerminalScreen *
  activeScreen(6),

  /// Whether the cursor is visible (DEC mode 25).
  ///
  /// Output type: bool *
  cursorVisible(7),

  /// Current Kitty keyboard protocol flags.
  ///
  /// Output type: KittyKeyFlags * (uint8_t *)
  kittyKeyboardFlags(8),

  /// Scrollbar state for the terminal viewport.
  ///
  /// This may be expensive to calculate depending on where the viewport
  /// is (arbitrary pins are expensive). The caller should take care to only
  /// call this as needed and not too frequently.
  ///
  /// Output type: TerminalScrollbar *
  scrollbar(9),

  /// The current SGR style of the cursor.
  ///
  /// This is the style that will be applied to newly printed characters.
  ///
  /// Output type: Style *
  cursorStyle(10),

  /// Whether any mouse tracking mode is active.
  ///
  /// Returns true if any of the mouse tracking modes (X10, normal, button,
  /// or any-event) are enabled.
  ///
  /// Output type: bool *
  mouseTracking(11),

  /// The terminal title as set by escape sequences (e.g. OSC 0/2).
  ///
  /// Returns a borrowed string. The pointer is valid until the next call
  /// to ghostty_terminal_vt_write() or ghostty_terminal_reset(). An empty
  /// string (len=0) is returned when no title has been set.
  ///
  /// Output type: String *
  title(12),

  /// The terminal's current working directory as set by escape sequences
  /// (e.g. OSC 7).
  ///
  /// Returns a borrowed string. The pointer is valid until the next call
  /// to ghostty_terminal_vt_write() or ghostty_terminal_reset(). An empty
  /// string (len=0) is returned when no pwd has been set.
  ///
  /// Output type: String *
  pwd(13),

  /// The total number of rows in the active screen including scrollback.
  ///
  /// Output type: size_t *
  totalRows(14),

  /// The number of scrollback rows (total rows minus viewport rows).
  ///
  /// Output type: size_t *
  scrollbackRows(15),

  /// The total width of the terminal in pixels.
  ///
  /// This is cols * cell_width_px as set by ghostty_terminal_resize().
  ///
  /// Output type: uint32_t *
  widthPx(16),

  /// The total height of the terminal in pixels.
  ///
  /// This is rows * cell_height_px as set by ghostty_terminal_resize().
  ///
  /// Output type: uint32_t *
  heightPx(17),

  /// The effective foreground color (override or default).
  ///
  /// Returns GHOSTTY_NO_VALUE if no foreground color is set.
  ///
  /// Output type: ColorRgb *
  colorForeground(18),

  /// The effective background color (override or default).
  ///
  /// Returns GHOSTTY_NO_VALUE if no background color is set.
  ///
  /// Output type: ColorRgb *
  colorBackground(19),

  /// The effective cursor color (override or default).
  ///
  /// Returns GHOSTTY_NO_VALUE if no cursor color is set.
  ///
  /// Output type: ColorRgb *
  colorCursor(20),

  /// The current 256-color palette.
  ///
  /// Output type: ColorRgb[256] *
  colorPalette(21),

  /// The default foreground color (ignoring any OSC override).
  ///
  /// Returns GHOSTTY_NO_VALUE if no default foreground color is set.
  ///
  /// Output type: ColorRgb *
  colorForegroundDefault(22),

  /// The default background color (ignoring any OSC override).
  ///
  /// Returns GHOSTTY_NO_VALUE if no default background color is set.
  ///
  /// Output type: ColorRgb *
  colorBackgroundDefault(23),

  /// The default cursor color (ignoring any OSC override).
  ///
  /// Returns GHOSTTY_NO_VALUE if no default cursor color is set.
  ///
  /// Output type: ColorRgb *
  colorCursorDefault(24),

  /// The default 256-color palette (ignoring any OSC overrides).
  ///
  /// Output type: ColorRgb[256] *
  colorPaletteDefault(25),

  /// The Kitty image storage limit in bytes for the active screen.
  ///
  /// A value of zero means the Kitty graphics protocol is disabled.
  /// Returns GHOSTTY_NO_VALUE when Kitty graphics are disabled at build time.
  ///
  /// Output type: uint64_t *
  kittyImageStorageLimit(26),

  /// Whether the file medium is enabled for Kitty image loading on the
  /// active screen.
  ///
  /// Returns GHOSTTY_NO_VALUE when Kitty graphics are disabled at build time.
  ///
  /// Output type: bool *
  kittyImageMediumFile(27),

  /// Whether the temporary file medium is enabled for Kitty image loading
  /// on the active screen.
  ///
  /// Returns GHOSTTY_NO_VALUE when Kitty graphics are disabled at build time.
  ///
  /// Output type: bool *
  kittyImageMediumTempFile(28),

  /// Whether the shared memory medium is enabled for Kitty image loading
  /// on the active screen.
  ///
  /// Returns GHOSTTY_NO_VALUE when Kitty graphics are disabled at build time.
  ///
  /// Output type: bool *
  kittyImageMediumSharedMem(29),

  /// The Kitty graphics image storage for the active screen.
  ///
  /// Returns a borrowed pointer to the image storage. The pointer is valid
  /// until the next mutating terminal call (e.g. ghostty_terminal_vt_write()
  /// or ghostty_terminal_reset()).
  ///
  /// Returns GHOSTTY_NO_VALUE when Kitty graphics are disabled at build time.
  ///
  /// Output type: KittyGraphics *
  kittyGraphics(30),

  /// The active screen's current selection.
  ///
  /// On success, writes an untracked snapshot of the terminal-owned selection
  /// to the caller-provided Selection. The GhosttySelection struct is
  /// caller-owned and may be kept, but the grid references inside it are
  /// untracked borrowed references into the active screen. They are only valid
  /// until the next mutating terminal call, such as ghostty_terminal_set(),
  /// ghostty_terminal_vt_write(), ghostty_terminal_resize(), or
  /// ghostty_terminal_reset().
  ///
  /// Returns GHOSTTY_NO_VALUE when there is no active selection.
  ///
  /// Output type: Selection *
  selection(31),

  /// Whether the viewport is currently pinned to the active area.
  ///
  /// This is true when the viewport is following the active terminal area,
  /// and false when the user has scrolled into history.
  ///
  /// Output type: bool *
  viewportActive(32);

  final int value;
  const TerminalData(this.value);

  static TerminalData fromValue(int value) => switch (value) {
    0 => invalid,
    1 => cols,
    2 => rows,
    3 => cursorX,
    4 => cursorY,
    5 => cursorPendingWrap,
    6 => activeScreen,
    7 => cursorVisible,
    8 => kittyKeyboardFlags,
    9 => scrollbar,
    10 => cursorStyle,
    11 => mouseTracking,
    12 => title,
    13 => pwd,
    14 => totalRows,
    15 => scrollbackRows,
    16 => widthPx,
    17 => heightPx,
    18 => colorForeground,
    19 => colorBackground,
    20 => colorCursor,
    21 => colorPalette,
    22 => colorForegroundDefault,
    23 => colorBackgroundDefault,
    24 => colorCursorDefault,
    25 => colorPaletteDefault,
    26 => kittyImageStorageLimit,
    27 => kittyImageMediumFile,
    28 => kittyImageMediumTempFile,
    29 => kittyImageMediumSharedMem,
    30 => kittyGraphics,
    31 => selection,
    32 => viewportActive,
    _ => throw ArgumentError('Unknown value for TerminalData: $value'),
  };
}

/// Terminal option identifiers.
///
/// These values are used with ghostty_terminal_set() to configure
/// terminal callbacks and associated state.
///
/// @ingroup terminal
enum TerminalOption {
  /// Opaque userdata pointer passed to all callbacks.
  ///
  /// Input type: void*
  userdata(0),

  /// Callback invoked when the terminal needs to write data back
  /// to the pty (e.g. in response to a DECRQM query or device
  /// status report). Set to NULL to ignore such sequences.
  ///
  /// Input type: TerminalWritePtyFn
  writePty(1),

  /// Callback invoked when the terminal receives a BEL character
  /// (0x07). Set to NULL to ignore bell events.
  ///
  /// Input type: TerminalBellFn
  bell(2),

  /// Callback invoked when the terminal receives an ENQ character
  /// (0x05). Set to NULL to send no response.
  ///
  /// Input type: TerminalEnquiryFn
  enquiry(3),

  /// Callback invoked when the terminal receives an XTVERSION query
  /// (CSI > q). Set to NULL to report the default "libghostty" string.
  ///
  /// Input type: TerminalXtversionFn
  xtversion(4),

  /// Callback invoked when the terminal title changes via escape
  /// sequences (e.g. OSC 0 or OSC 2). Set to NULL to ignore title
  /// change events.
  ///
  /// Input type: TerminalTitleChangedFn
  titleChanged(5),

  /// Callback invoked in response to XTWINOPS size queries
  /// (CSI 14/16/18 t). Set to NULL to silently ignore size queries.
  ///
  /// Input type: TerminalSizeFn
  size(6),

  /// Callback invoked in response to a color scheme device status
  /// report query (CSI ? 996 n). Return true and fill the out pointer
  /// to report the current scheme, or return false to silently ignore.
  /// Set to NULL to ignore color scheme queries.
  ///
  /// Input type: TerminalColorSchemeFn
  colorScheme(7),

  /// Callback invoked in response to a device attributes query
  /// (CSI c, CSI > c, or CSI = c). Return true and fill the out
  /// pointer with response data, or return false to silently ignore.
  /// Set to NULL to ignore device attributes queries.
  ///
  /// Input type: TerminalDeviceAttributesFn
  deviceAttributes(8),

  /// Set the terminal title manually.
  ///
  /// The string data is copied into the terminal. A NULL value pointer
  /// clears the title (equivalent to setting an empty string).
  ///
  /// Input type: String*
  title(9),

  /// Set the terminal working directory manually.
  ///
  /// The string data is copied into the terminal. A NULL value pointer
  /// clears the pwd (equivalent to setting an empty string).
  ///
  /// Input type: String*
  pwd(10),

  /// Set the default foreground color.
  ///
  /// A NULL value pointer clears the default (unset).
  ///
  /// Input type: ColorRgb*
  colorForeground(11),

  /// Set the default background color.
  ///
  /// A NULL value pointer clears the default (unset).
  ///
  /// Input type: ColorRgb*
  colorBackground(12),

  /// Set the default cursor color.
  ///
  /// A NULL value pointer clears the default (unset).
  ///
  /// Input type: ColorRgb*
  colorCursor(13),

  /// Set the default 256-color palette.
  ///
  /// The value must point to an array of exactly 256 ColorRgb values.
  /// A NULL value pointer resets to the built-in default palette.
  ///
  /// Input type: ColorRgb[256]*
  colorPalette(14),

  /// Set the Kitty image storage limit in bytes.
  ///
  /// Applied to all initialized screens (primary and alternate).
  /// A value of zero disables the Kitty graphics protocol entirely,
  /// deleting all stored images and placements. A NULL value pointer
  /// is equivalent to zero (disables). Has no effect when Kitty graphics
  /// are disabled at build time.
  ///
  /// Input type: uint64_t*
  kittyImageStorageLimit(15),

  /// Enable or disable Kitty image loading via the file medium.
  ///
  /// A NULL value pointer is a no-op. Has no effect when Kitty graphics
  /// are disabled at build time.
  ///
  /// Input type: bool*
  kittyImageMediumFile(16),

  /// Enable or disable Kitty image loading via the temporary file medium.
  ///
  /// A NULL value pointer is a no-op. Has no effect when Kitty graphics
  /// are disabled at build time.
  ///
  /// Input type: bool*
  kittyImageMediumTempFile(17),

  /// Enable or disable Kitty image loading via the shared memory medium.
  ///
  /// A NULL value pointer is a no-op. Has no effect when Kitty graphics
  /// are disabled at build time.
  ///
  /// Input type: bool*
  kittyImageMediumSharedMem(18),

  /// Set the maximum bytes the APC handler will buffer for all protocols.
  /// This prevents malicious input from causing unbounded memory allocation.
  /// A NULL value pointer removes all overrides, reverting to the built-in
  /// defaults.
  ///
  /// Input type: size_t*
  apcMaxBytes(19),

  /// Set the maximum bytes the APC handler will buffer for Kitty graphics
  /// protocol data. A NULL value pointer removes the override, reverting
  /// to the built-in default.
  ///
  /// Input type: size_t*
  apcMaxBytesKitty(20),

  /// Set the active screen selection.
  ///
  /// The value must point to a Selection whose grid references are
  /// valid for this terminal's active screen at the time of the call. The
  /// terminal copies the selection immediately and converts it to
  /// terminal-owned tracked state, so the Selection struct and its
  /// untracked grid references do not need to outlive this call.
  ///
  /// Passing NULL clears the active screen selection.
  ///
  /// Input type: Selection*
  selection(21),

  /// Set the default cursor style used by DECSCUSR reset (CSI 0 q).
  ///
  /// A NULL value pointer resets to the built-in default block cursor.
  ///
  /// Input type: TerminalCursorStyle*
  defaultCursorStyle(22),

  /// Set whether the default cursor should blink when reset by DECSCUSR
  /// (CSI 0 q).
  ///
  /// A NULL value pointer resets to the built-in default of not blinking.
  ///
  /// Input type: bool*
  defaultCursorBlink(23),

  /// Enable or disable Glyph Protocol APC handling.
  ///
  /// When disabled, Glyph Protocol APC sequences are ignored and no
  /// support/query/register/clear responses are emitted. Disabling also clears
  /// the terminal session's glyph glossary. A NULL value pointer is a no-op.
  ///
  /// Input type: bool*
  glyphProtocol(24),

  /// Callback invoked when the terminal pwd changes via escape
  /// sequences (OSC 7, OSC 9, or OSC 1337 CurrentDir). Set to NULL
  /// to ignore pwd change events.
  ///
  /// Input type: TerminalPwdChangedFn
  pwdChanged(25);

  final int value;
  const TerminalOption(this.value);

  static TerminalOption fromValue(int value) => switch (value) {
    0 => userdata,
    1 => writePty,
    2 => bell,
    3 => enquiry,
    4 => xtversion,
    5 => titleChanged,
    6 => size,
    7 => colorScheme,
    8 => deviceAttributes,
    9 => title,
    10 => pwd,
    11 => colorForeground,
    12 => colorBackground,
    13 => colorCursor,
    14 => colorPalette,
    15 => kittyImageStorageLimit,
    16 => kittyImageMediumFile,
    17 => kittyImageMediumTempFile,
    18 => kittyImageMediumSharedMem,
    19 => apcMaxBytes,
    20 => apcMaxBytesKitty,
    21 => selection,
    22 => defaultCursorStyle,
    23 => defaultCursorBlink,
    24 => glyphProtocol,
    25 => pwdChanged,
    _ => throw ArgumentError('Unknown value for TerminalOption: $value'),
  };
}

/// Terminal screen identifier.
///
/// Identifies which screen buffer is active in the terminal.
///
/// @ingroup terminal
enum TerminalScreen {
  /// The primary (normal) screen.
  primary(0),

  /// The alternate screen.
  alternate(1);

  final int value;
  const TerminalScreen(this.value);

  static TerminalScreen fromValue(int value) => switch (value) {
    0 => primary,
    1 => alternate,
    _ => throw ArgumentError('Unknown value for TerminalScreen: $value'),
  };
}

/// Scroll viewport behavior tag.
///
/// @ingroup terminal
enum TerminalScrollViewportTag {
  /// Scroll to the top of the scrollback.
  top(0),

  /// Scroll to the bottom (active area).
  bottom(1),

  /// Scroll by a delta amount (up is negative).
  delta(2);

  final int value;
  const TerminalScrollViewportTag(this.value);

  static TerminalScrollViewportTag fromValue(int value) => switch (value) {
    0 => top,
    1 => bottom,
    2 => delta,
    _ => throw ArgumentError(
      'Unknown value for TerminalScrollViewportTag: $value',
    ),
  };
}
